### ISSUE TITLE
Incorrect import in utils.py

### ISSUE THREAD

**Issue by picaultj** [BDonnot/leap_net#3]
The import of PandaPowerBackend does not match the last version of grid2op.

**Comment by picaultj** [comment]
updated file

[utils.zip](https://github.com/BDonnot/leap_net/files/6030916/utils.zip)

**Comment by BDonnot** [comment]
Hello,
Thanks for the update. The error was on the "leap_net/proxy/utils.py" file, right ?

Benjamin

**Comment by picaultj** [comment]
yes, see the updated file in the comment above.

**Comment by BDonnot** [comment]
Would have been easier to make a pull request for this issue :-)
